#This schedule performs the baseline trainning for mobilenet_cifar10
#

version: 1
lr_schedulers:
  #learning rate decay scheduler
  baseline_lr:
    class: MultiStepLR
    milestones: [200, 400]
    gamma: 0.1

policies:
  - lr_scheduler:
      instance_name: baseline_lr
    starting_epoch: 0
    ending_epoch: 600
    frequency: 1
